import React, { useEffect } from "react";
import { AnimatePresence, motion } from "framer-motion";
import { useCart } from "../../context/CartContext";
import { formatPrice } from "../../catalog/productService";

export default function CartDrawer() {
  const { isCartOpen, closeCart, cartItems, updateQty, removeFromCart, subtotal } = useCart();
  useEffect(() => { if (!isCartOpen) return; const closeOnEscape = (event) => event.key === "Escape" && closeCart(); document.addEventListener("keydown", closeOnEscape); document.body.style.overflow = "hidden"; return () => { document.removeEventListener("keydown", closeOnEscape); document.body.style.overflow = ""; }; }, [isCartOpen, closeCart]);
  return <AnimatePresence>{isCartOpen && <motion.div className="fixed inset-0 z-50" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}><button type="button" aria-label="Close bag" onClick={closeCart} className="absolute inset-0 bg-black/45"/><motion.aside className="absolute right-0 top-0 flex h-full w-full max-w-[470px] flex-col bg-[#f7f5f0] text-black sm:w-[470px]" initial={{ x: "100%" }} animate={{ x: 0 }} exit={{ x: "100%" }} transition={{ type: "spring", stiffness: 300, damping: 32 }}><header className="flex items-center justify-between border-b border-black/10 px-5 py-5 sm:px-7"><div><p className="eyebrow">GRV / Bag</p><h2 className="brand-wordmark mt-1 text-2xl">Your selection</h2></div><button type="button" onClick={closeCart} className="grid h-10 w-10 place-items-center rounded-full border border-black/20 text-xl transition hover:border-[#EF4824] hover:text-[#EF4824]">×</button></header><div className="flex-1 overflow-y-auto px-5 py-6 sm:px-7">{cartItems.length === 0 ? <div className="grid min-h-64 place-items-center text-center"><div><p className="brand-wordmark text-4xl text-[#EF4824]">GRV</p><p className="mt-3 text-sm text-muted">Your bag is ready for your next move.</p><button onClick={closeCart} className="mt-6 rounded-full bg-[#EF4824] px-6 py-3 text-sm text-white">Continue shopping</button></div></div> : <div className="space-y-5">{cartItems.map((item) => <article key={item.id} className="flex gap-4 border-b border-black/10 pb-5"><img src={item.product.image} alt={item.product.name} className="h-28 w-22 rounded-[18px] bg-neutral object-cover sm:h-32 sm:w-24"/><div className="min-w-0 flex-1"><div className="flex gap-3"><div className="flex-1"><p className="text-sm font-medium">{item.product.name}</p><p className="mt-1 text-xs text-muted">{formatPrice(item.product.price)}</p></div><button onClick={() => removeFromCart(item.id)} className="text-xs text-muted underline hover:text-[#EF4824]">Remove</button></div><div className="mt-6 flex items-center justify-between"><div className="flex items-center rounded-full border border-black/15 bg-white"><button className="h-8 w-8" onClick={() => updateQty(item.id, item.qty - 1)}>−</button><span className="w-7 text-center text-xs">{item.qty}</span><button className="h-8 w-8" onClick={() => updateQty(item.id, item.qty + 1)}>+</button></div><p className="text-sm font-medium">{formatPrice(item.product.price * item.qty)}</p></div></div></article>)}</div>}</div><footer className="border-t border-black/10 bg-white px-5 py-5 sm:px-7"><div className="flex justify-between text-sm"><span>Subtotal</span><strong>{formatPrice(subtotal)}</strong></div><p className="mt-2 text-xs text-muted">Taxes and shipping calculated at checkout.</p><button className="mt-5 w-full rounded-full bg-[#EF4824] py-4 text-sm font-medium text-white transition hover:bg-black">Secure checkout →</button></footer></motion.aside></motion.div>}</AnimatePresence>;
}
